name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 03_ExampleAppZephyr/example-application

      - name: Initialize
        working-directory: ./03_ExampleAppZephyr/
        run: |
          pip3 install -U west
          west init -l ./example-application
          west update
          pip3 install -r ./zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: ./03_ExampleAppZephyr/example-application
        run: |
          west build -b controller_l432kc -s app

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: 03_ExampleAppZephyr/example-application/build/zephyr/zephyr.*
